_.max()  should compare between numbers
jashkenas/underscore pull request #2896
Opened 2020-12-18 06:09 UTC by anderlaw

As mentioned in the underscore document, _.max function should compare items by numbers only

2020-12-18 15:03 UTC, jgonggrijp requested changes
Thanks @anderlaw for taking the effor to submit a PR. You are right to point out that there is a mismatch between the documentation and the actual logic. Good catch!

However, I think you need to take a different approach. The documentation is broken, not the logic. I did some research, and found that the implementation has never ignored non-numeric values; rather, the false claim that it does so was added to the documentation in #2561 in a failed attempt to make the documentation more accurate.

Of course, you *could* decide to update the logic so that it reflects the documentation, but I think updating the documentation to reflect the logic is a better choice here, for the following reasons:

- In this case, changing the logic is a breaking change.
- The current logic is more general; it could work for strings, if `result` weren't hardcoded to start with `-Infinity`. I'm planning to fix that in version 2.0; see #2688.

So I suggest that you undo the code changes and instead update the `index.html` to replace the sentence "Non-numerical values in list will be ignored" by "This function can currently only compare numbers reliably". If you do so, please make sure to also update the documentation for `_.min`. You'll then still get the credits.

Does that sound like a plan?

2020-12-21 07:03 UTC, anderlaw commented
Thanks for the response, I'd like to do that

2020-12-21 10:38 UTC, jgonggrijp approved these changes

2020-12-21 10:40 UTC, merged

2020-12-21 10:40 UTC, jgonggrijp commented
Congratulations with your first contribution to Underscore, @anderlaw!