Added dark mode button
jashkenas/underscore pull request #2980
Opened 2023-05-01 15:21 UTC by yogi-25

I have added dark mode button and it is able to change the state ON and OFF.

2023-05-02 20:32 UTC, jgonggrijp requested changes
Thank you for making a contribution!

The change is welcome and it works, but:

- [ ] the styling needs refinement, and
- [ ] I think it would be better if dark mode is automatically selected for people who prefer it.

Please take a look at [the screenshot by @gprasanth](https://github.com/jashkenas/underscore/issues/2909) and [his gist](https://gist.github.com/gprasanth/aae06b6e437d00f37af3bddc78776f57) in which he shared the CSS that made it work, including the media selector that takes care of selecting dark mode automatically.

This is what your version of dark mode currently looks like in Safari:

![screenshot](https://user-images.githubusercontent.com/1540185/235779096-1861a173-38b7-4c9f-a429-6035ecd1ca2b.png)

2023-05-04 17:17 UTC, prabodhmeshram commented on index.html
> +    </script>
Formatting seems off here

2023-05-04 17:17 UTC, prabodhmeshram commented on index.html
> +        }
Another lint issue

2026-07-20 03:13 UTC, jgonggrijp commented
This is obsolete as of #2996. Sorry for not closing it earlier.

2026-07-20 03:13 UTC, closed without merging