Add _.VERSION to the documentation
jashkenas/underscore pull request #2998
Opened 2024-10-15 19:24 UTC by Aurimas-stack

Added `_.VERSION` as per https://github.com/jashkenas/underscore/issues/2992 issue.

In my opinion placing it under `Notes` should be more than enough as `utility` section seems to include more complex methods than this one.

![version](https://github.com/user-attachments/assets/16ab13b8-a5c7-4177-9bbf-89364b2eb6f9)

2024-10-15 20:17 UTC, jgonggrijp requested changes
Thank you for making a contribution. @Aurimas-stack!

Please put this in the Utility section and also add it to the table of contents so that people can find it by typing. The Notes section is for comments about the semantics of functions that apply to more than one function.

I have a few nitpicks as well, see below. Otherthan that, I am content.

2024-10-15 20:17 UTC, jgonggrijp commented on index.html
> +      <p id="relational-operator-note">
It is OK to copy-paste another section and then edit, but you need to give the new section its own unique `id`. :-)

2024-10-15 20:17 UTC, jgonggrijp commented on index.html
> +        <b class="header">Underscore version</b>
For consistency with the other API sections, I suggest naming this after the actual symbol.

```suggestion
        <b class="header">VERSION</b>
```

2024-10-15 20:17 UTC, jgonggrijp commented on index.html
> +        It's possible to get current Underscore version via
```suggestion
        It is possible to get the current Underscore version via
```

2024-10-15 20:17 UTC, jgonggrijp commented on index.html
> +        <pre>_.VERSION => 1.13.7</pre>
The characters `<`, `>`, `&`, `"` and `'` need to be escaped even within `<pre>`.

```suggestion
        <pre>_.VERSION =&gt; 1.13.7</pre>
```

2024-10-16 07:18 UTC, Aurimas-stack commented
Hey @jgonggrijp ,

I've made the requested changes, please review them, cheers.

2024-10-16 10:55 UTC, jgonggrijp approved these changes
Thanks! And congratulations with your first contribution!

2024-10-16 10:57 UTC, merged

2025-04-09 15:57 UTC, jgonggrijp commented
Now published on the website. Sorry for the delay.